# Generated by Django 3.1.1 on 2020-10-31 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingTitle', models.CharField(max_length=64)),
                ('listingCategory', models.CharField(max_length=38)),
                ('listingDesc', models.CharField(max_length=500)),
                ('imageUrl', models.CharField(max_length=500)),
                ('currentPrice', models.PositiveIntegerField()),
                ('closed', models.BooleanField(default=False)),
                ('listedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
